# ================= LANG SYSTEM =================
TEXTS = {
    "ar": {
        "menu": "مرحبا بك في Trackly Bot 🚀",
        "add_link": "➕ إضافة رابط",
        "list_links": "📁 عرض الروابط",
        "delete_link": "🗑️ حذف رابط",
        "help": "ℹ️ الدعم",
        "help_message": "للتواصل والدعم:\n✉️ البريد الإلكتروني: 7assanosama@gmail.com\n📞 واتساب: https://wa.me/201029231051\n✈️ تيليجرام: @osmo1051",
        "send_link": "ابعت الرابط:",
        "invalid_url": "❌ رابط غير صالح",
        "added": "✅ تم الإضافة",
        "deleted": "تم الحذف",
        "no_links": "لا يوجد روابط",
        "links_title": "📁 روابطك:",
        "cancel": "تم الإلغاء",
        "lang": "🌐 تغيير اللغة",
        "choose_lang": "اختر اللغة:",
        "plans": "💎 خطط التسعير",
        "plans_info": "💳 **خطط التسعير المتوفرة:**\n\n🆓 **الخطة المجانية:** 1 رابط فقط.\n🪙 **الخطة الأساسية:** 10 روابط.\n💎 **الخطة الاحترافية:** عدد لا محدود من الروابط.\n\nللترقية، يرجى التواصل معنا عبر:\n✉️ البريد الإلكتروني: 7assanosama@gmail.com\n📞 واتساب: https://wa.me/201029231051\n✈️ تيليجرام: @osmo1051",
        "limit_reached": "⚠️ لقد وصلت للحد الأقصى للروابط في خطتك الحالية.\nيرجى الترقية لإضافة المزيد من الروابط بالضغط على زر '💎 خطط التسعير'.",
        "diff_before": "قبل",
        "diff_after": "بعد",
        "diff_truncated": "\n...\n(مختصر)",
        "site_changed": "🚨 **تحديث جديد في الموقع:**\n{url}\n\n{diff_text}",
        "additions": "إضافات جديدة:",
        "deletions": "نصوص محذوفة:",
    },
    "en": {
        "menu": "Welcome to Trackly Bot 🚀",
        "add_link": "➕ Add link",
        "list_links": "📁 My links",
        "delete_link": "🗑️ Delete link",
        "help": "ℹ️ support",
        "help_message": "For contact and support:\n✉️ Email: 7assanosama@gmail.com\n📞 WhatsApp: https://wa.me/201029231051\n✈️ Telegram: @osmo1051",
        "send_link": "Send the link:",
        "invalid_url": "❌ Invalid URL",
        "added": "✅ Added successfully",
        "deleted": "Deleted",
        "no_links": "No links found",
        "links_title": "📁 Your links:",
        "cancel": "Cancelled",
        "lang": "🌐 Language",
        "choose_lang": "Choose language:",
        "plans": "💎 Pricing Plans",
        "plans_info": "💳 **Available Pricing Plans:**\n\n🆓 **Free Plan:** 1 link only.\n🪙 **Basic Plan:** 10 links.\n💎 **Pro Plan:** Unlimited links.\n\nTo upgrade, please contact us via:\n✉️ Email: 7assanosama@gmail.com\n📞 WhatsApp: https://wa.me/201029231051\n✈️ Telegram: @osmo1051",
        "limit_reached": "⚠️ You have reached the maximum links limit for your current plan.\nPlease upgrade to add more links by clicking '💎 Pricing Plans'.",
        "diff_before": "Before",
        "diff_after": "After",
        "diff_truncated": "\n...\n(truncated)",
        "site_changed": "🚨 **Website update:**\n{url}\n\n{diff_text}",
        "additions": "Added:",
        "deletions": "Removed:",
    }
}